# Generated by Django 2.2.10 on 2020-08-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='color',
            field=models.CharField(default='pink', max_length=10),
            preserve_default=False,
        ),
    ]
