# Generated by Django 3.2.18 on 2023-02-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_confession_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='site',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
